Repository ashutoshgithubs/iemhacks_DEV-G, pull requests merged in 2024-05, with the labels that each got.

#63 github workflow action to greet contributors when issue or pr is created
  .github/workflows/issue_greeting.yaml
  .github/workflows/pr_greeting.yaml
Labels: enhancement, gssoc, level2

#60 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc, level1

#73 feat: automate greetings using github bot
  .github/workflows/greetings.yml
  .github/workflows/issue_greeting.yaml
  .github/workflows/pr_greeting.yaml
Labels: enhancement, gssoc, level2

#87 update readme
  README.md
Labels: documentation, gssoc, level1

#88 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc, level1

#65 Solved Issue #62 . Landing page title overlapping at ~730px width.
  src/pages/TopHome.jsx
Labels: bug, good first issue, gssoc, level1

#67 About us redirect change
  src/App.js
Labels: bug, good first issue, gssoc, level1

#99 Countup feature added to the about us page
  .env.sample
  package-lock.json
  package.json
  src/components/core/About/Stats.jsx
Labels: enhancement, React, gssoc, level2

#104 Reset password URL fix
  server/controllers/ResetPassword.js
Labels: bug, good first issue, gssoc, level1

#107 Reduced Code Duplication
  src/pages/TopHome.jsx
Labels: gssoc, level1
